version: "3.9"
services:
  db:
    image: springfinance.azurecr.io/db:latest
    volumes:
      - dbdata:/var/mysql/db
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: SA53Team6
      MYSQL_DATABASE: spring_finance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
  backend:
    image: springfinance.azurecr.io/backend:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_finance?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - backend:/usr/java/app
    links:
      - db:db
    networks:
      - app-network
  frontend:
    depends_on:
      - backend
    image: springfinance.azurecr.io/frontend:latest
    volumes:
      - frontend:/usr/node/app
    restart: always
    networks:
      - app-network
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      BROWSER: none
volumes:
  dbdata:
    driver: azure_file
    driver_opts:
      share_name: dbdata
      storage_account_name: springfinance
  frontend:
    driver: azure_file
    driver_opts:
      share_name: frontend
      storage_account_name: springfinance
  backend:
    driver: azure_file
    driver_opts:
      share_name: backend
      storage_account_name: springfinance
networks:
  app-network:
    driver: bridge
